### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by ry85** [NVlabs/tiny-cuda-nn#167]
Hi,
I am getting the following error "cannot find -lcuda", when installing via a local clone of the tcnn repo,

git clone https://github.com/NVlabs/tiny-cuda-nn.git
cd bindings/torch
python setup.py install

I had lcuda installed, but unfortunately it is not getting found. I find this thread https://stackoverflow.com/a/34256630 which suggests  modifying the compile file to explicitly provide the path of the lcuda library (-L/us/lib/x86_64-linux-gnu , this directory contains all cuda libraries including lcuda).

Can you please help. I am completely new to this.

**Comment by aejion** [comment]
@ry85 have you solved this problem? i met the same problem as well

**Comment by RohanChacko** [comment]
I face the same error. 

I had to install GCC 9.3.0 inside my conda env since the system GCC ver. is 5.4.0 and cannot compile tcnn. 
The `libcuda.so` file is in `/usr/local/cuda-11.3/lib64/stubs/` and my `LD_LIBRARY_PATH=/usr/local/cuda-11.3/lib64`. But my conda GCC is not able to locate this file. 

I am not sure how to modify the CMakelists.txt file to add an explicit path to the file. Any help would be appreciated. Thanks!

**Comment by jhzgjhzg** [comment]
I also reported this error when using this command: python setup.py install. Is there any solution
Building PyTorch extension for tiny-cuda-nn version 1.6
Obtained compute capability 70 from PyTorch
running install
/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
creating tinycudann.egg-info
writing tinycudann.egg-info/PKG-INFO
writing dependency_links to tinycudann.egg-info/dependency_links.txt
writing top-level names to tinycudann.egg-info/top_level.txt
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
reading manifest file 'tinycudann.egg-info/SOURCES.txt'
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib.linux-x86_64-cpython-310
creating build/lib.linux-x86_64-cpython-310/tinycudann
copying tinycudann/modules.py -> build/lib.linux-x86_64-cpython-310/tinycudann
copying tinycudann/__init__.py -> build/lib.linux-x86_64-cpython-310/tinycudann
copying tinycudann/bindings.cpp -> build/lib.linux-x86_64-cpython-310/tinycudann
running build_ext
/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.4) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'tinycudann_bindings_70._C' extension
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/dependencies
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/dependencies/fmt
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/dependencies/fmt/src
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/src
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-310
creating /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-310/tinycudann
Emitting ninja build file /home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-310/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '/home/nhy123456/nerfstudio/tiny-cuda-nn/dependencies/fmt/src/format.cc', needed by '/home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/dependencies/fmt/src/format.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nhy123456/nerfstudio/tiny-cuda-nn/bindings/torch/setup.py", line 127, in <module>
    setup(
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
    self.run_command(cmd)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/command/install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
    cmd_obj.run()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 84, in run
    _build_ext.run(self)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 547, in build_extension
    objects = self.compiler.compile(
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 586, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/nhy123456/.conda/envs/nerfstudio/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by jzhangbs** [comment]
I solve this problem by putting the dir with libcuda.so in LIBRARY_PATH (instead of LD_LIBRARY_PATH).

**Comment by Talegqz** [comment]
> I solve this problem by putting the dir with libcuda.so in LIBRARY_PATH (instead of LD_LIBRARY_PATH).

Can you provide more detail steps? Thanks for your help!!!
