### ISSUE TITLE
tiny cuda install error

### ISSUE THREAD

**Issue by amorell1234** [NVlabs/tiny-cuda-nn#214]
(nerfstudio) C:\Users\17069\Desktop\NS>pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\17069\appdata\local\temp\pip-req-build-lwxzpvk6
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\17069\AppData\Local\Temp\pip-req-build-lwxzpvk6'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 8e6e242f36dd197134c9b9275a8e5108a8e3af78
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\17069\AppData\Local\Temp\pip-req-build-lwxzpvk6\bindings/torch\setup.py", line 3, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

What is causing this?

**Comment by mints7** [comment]
try to install pytorch

**Comment by newforests** [comment]
> try to install pytorch

Could you tell me how to solve this problem？

**Comment by grofattila** [comment]
> > try to install pytorch
> 
> Could you tell me how to solve this problem？

pip install torch

**Comment by jaggzh** [comment]
I'm getting the same error.
Torch is installed -- I'm in a venv and, when running python, "import torch" works fine.
Note that the installation is run from nerfstudio installation instructions:
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
Which I also modified, for bash to not ignore the # comment, to:
`pip install 'git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch'`

I've yet to solve it.

**Comment by hashFactory** [comment]
I just encountered the same issue. I used to be able to go like this:
```bash
export PYTHONPATH="/tmp/tri/pip/"
export PIP="--target '/tmp/tri/pip/' --cache-dir '/tmp/tri/cache/'"

python3 -m pip install $PIP --upgrade pip setuptools ninja torch==1.12.1+cu113 torchvision==0.13.1+cu113 functorch==0.2.1 torchmetrics -f https://download.pytorch.org/whl/torch_stable.html
python3 -m pip install $PIP --upgrade 'git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch'
...
```

But this broke for me today giving me the same `No module named 'torch'` error. Not sure what the problem is but I managed to get it working again using pyenv.

```bash
# install pyenv to alternative location
export PYENV_ROOT="/tmp/tri/pyenv"                                                                                                                                                  
curl https://pyenv.run | bash                                                                                                                                                       
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"                                                                                                                  
eval "$(pyenv init -)"

# setup new env
pyenv install 3.9.16
pyenv virtualenv 3.9.16 venv_nerf
pyenv activate venv_nerf

pip install --upgrade pip setuptools ninja torch==1.12.1+cu113 torchvision==0.13.1+cu113 functorch==0.2.1 torchmetrics -f https://download.pytorch.org/whl/torch_stable.html
pip install --upgrade 'git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch'
...
```

**Comment by gautam-sh** [comment]
I was also getting the same error. Even after setting up the correct Python path in the virtual env, it was not able to find Torch. So instead of getting the Pytorch extension, I installed it from a local clone as mentioned in the readme file.

**Comment by hashFactory** [comment]
> I was also getting the same error. Even after setting up the correct Python path in the virtual env, it was not able to find Torch.

You're right, I just tried it again and ran into the same issues following my instructions. I was able to fix it again by omitting the pip upgrade to 23.1.2. Everything seems to work as expected with pip 23.0.1.

**Comment by michaelnoi** [comment]
I also installed from local clone and needed to additionally init the submodules again to make it work:
`git submodule update --init --recursive`

**Comment by valer-cara** [comment]
pip 23.0.1 here, getting the same error. Tried python 3.9, 3.10 and 3.11 so far.

**Comment by DinisMartinho** [comment]
I encountered the same error. I uninstalled all the packages I had installed with pip and then reinstalled tiny-cuda-nn following the Nerf Studio guide.

**Comment by jloveric** [comment]
Seeing this problem with pip 24 and 24.2 on ubuntu 22.04 which uses python3.10 and resolved changing pip to 23.0.1. Did see this error along the way ```DEPRECATION: tinycudann is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559``` so it seems the installation needs to be updated.

**Comment by AllorH** [comment]
I got the same problem even though torch is already installed in my virtual environment. Try `pip install pip==23.0.1` and it works.

**Comment by hassanm57** [comment]
SOLUTION THAT WORKED FOR ME:
do `pip install wheel` , then try if it works.


Another solution:
 Try `pip install pip==23.0.1` before.

**Comment by CrimsonCuttle** [comment]
Neither of these worked for me and im hitting my head very very hard with a comically large hammer

**Comment by dvdmc** [comment]
Maybe another solution would be to add 'torch' to the `setup.py` in this line https://github.com/NVlabs/tiny-cuda-nn/blob/dc44d0d50a68118160debb3c698fef28a2ee2d78/bindings/torch/setup.py#L260
Any thoughts?

**Comment by dvdmc** [comment]
Sorry, @CrimsonCuttle , my comment was actually referred to just the torch dependency. To me, using 'wheel' did the trick but i think that is just a patch and should be fixed in the setup.py.

As for your case:
For instaling CUDA in Ubuntu I follow this process which work every time: 
1. Install nvidia drivers ONLY using `sudo ubuntu-drivers autoinstall`. If you already have drivers installed with a different method, make sure to remove them. 
2. Install a CUDA version that, at least, is compatible with a modern pytorch version. For me, that if 12.8 at the time of this answer. Remove any other and make sure to add `nvcc` to the PATH env variable and cuda library to LD_LIBRARY_PATH as some software assume they exist.
3. Install the compatible pytorch library following the official guide.

I hope this helps.

**Comment by yccyenchicheng** [comment]
Maybe try 
```
pip install --no-build-isolation git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```
