### ISSUE TITLE
installation issue undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

### ISSUE THREAD

**Issue by YanhaoZhang** [NVlabs/tiny-cuda-nn#222]
Hi I am trying to install tiny cuda nn, but got the following error. 
``` shell
ERROR: Command errored out with exit status 1:
     command: /home/yanhao/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-wbn42yj0/bindings/torch/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-wbn42yj0/bindings/torch/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1hereegz
         cwd: /tmp/pip-req-build-wbn42yj0/bindings/torch
    Complete output (22 lines):
    Traceback (most recent call last):
      File "/home/yanhao/anaconda3/lib/python3.8/site-packages/torch/__init__.py", line 172, in _load_global_deps
        ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
      File "/home/yanhao/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/yanhao/anaconda3/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-wbn42yj0/bindings/torch/setup.py", line 3, in <module>
        import torch
      File "/home/yanhao/anaconda3/lib/python3.8/site-packages/torch/__init__.py", line 217, in <module>
        _load_global_deps()
      File "/home/yanhao/anaconda3/lib/python3.8/site-packages/torch/__init__.py", line 178, in _load_global_deps
        _preload_cuda_deps()
      File "/home/yanhao/anaconda3/lib/python3.8/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
        ctypes.CDLL(cublas_path)
      File "/home/yanhao/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: /home/yanhao/anaconda3/lib/python3.8/site-packages/nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
    ----------------------------------------
WARNING: Discarding git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I guess this might related to cudnn issue. However, I have installed cudnn to both system and conda. I was wondering if you could give me some suggestion? Thank you.

**Comment by YanhaoZhang** [comment]
Just in case someone might have a similar issue, here are some of the details on how I install `tinycudann` on my laptop with RTX3050, and CUDA 11.3.

``` shell
conda create -n xxx python=3.8
conda activate xxx
pip install torch==1.11.0 torchvision==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113

export TCNN_CUDA_ARCHITECTURES=86
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```
