### ISSUE TITLE
Installation issue on RTX 3070

### ISSUE THREAD

**Issue by YanhaoZhang** [NVlabs/tiny-cuda-nn#224]
Hi, I have compiled and installed it on my laptop with RTX 3050. However, I cannot compile it (both the linux compilation and the pytorch extension) on my desktop with RTX 3070. The cuda version is 11.3. 

The error for linux compilation is as follow when run `cmake . -DCMAKE_CUDA_ARCHITECTURES=86 -B build`
``` shell
- The CXX compiler identification is GNU 9.4.0
CMake Error at /usr/local/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:675 (message):
  Compiling the CUDA compiler identification source file
  "CMakeCUDACompilerId.cu" failed.

  Compiler: /usr/bin/nvcc

  Build flags:

  Id flags: --keep;--keep-dir;tmp;-gencode=arch=compute_86,code=sm_86 -v

  The output was:

  1

  nvcc fatal : Unsupported gpu architecture 'compute_86'

Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:6 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/share/cmake-3.20/Modules/CMakeDetermineCompilerId.cmake:47 (__determine_compiler_id_test)
  /usr/local/share/cmake-3.20/Modules/CMakeDetermineCUDACompiler.cmake:278 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:25 (project)

-- Configuring incomplete, errors occurred!
See also "/home/yanhao/anu_nerf/tiny-cuda-nn/build/CMakeFiles/CMakeOutput.log".
See also "/home/yanhao/anu_nerf/tiny-cuda-nn/build/CMakeFiles/CMakeError.log".
```

The error for pytorch extension is
``` shell
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-hrno4_ia
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-hrno4_ia
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 6ccf5ad7b03d15241ffbd392b3579168df73faa5
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-hrno4_ia/bindings/torch/setup.py", line 3, in <module>
          import torch
        File "/home/yanhao/anaconda3/envs/torch-ngp/lib/python3.8/site-packages/torch/__init__.py", line 199, in <module>
          from torch._C import *  # noqa: F403
      ImportError: /home/yanhao/anaconda3/lib/python3.8/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

I was wondering if other people got a similar issue. Plus, could you please give me some suggestions?
Thank you.

**Comment by YanhaoZhang** [comment]
A quick update: I can conduct Linux compilation by running `cmake . -B build -DCMAKE_CUDA_COMPILER=/usr/local/cuda-11.3/bin/nvcc`. However, I am still not able to compile the PyTorch extension.

**Comment by YanhaoZhang** [comment]
The pytorch compilation is solved by adding `export LD_LIBRARY_PATH="~/anaconda3/env/torch-ngp/lib/python3.8/site-packages/torch/lib:$LD_LIBRARY_PATH"`
