### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 75.

### ISSUE THREAD

**Issue by khayamgondal** [NVlabs/tiny-cuda-nn#230]
Hi. The following exception is thrown when I import tiny cuda via `import tinycudann `. I used cuda 11.3 on RTX 2060 MAX Q on Ubuntu 20.04 WSL to compile and install the package

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/khayam/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/khayam/anaconda3/envs/ngp_pl/lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann/modules.py", line 35, in <module>
    raise EnvironmentError(f"Could not find compatible tinycudann extension for compute capability {system_compute_capability}.")
OSError: Could not find compatible tinycudann extension for compute capability 75.
```

**Comment by khayamgondal** [comment]
Recompiling solved the problem
