### ISSUE TITLE
ImportError with PyTorch extensions

### ISSUE THREAD

**Issue by suddhu** [NVlabs/tiny-cuda-nn#284]
I've tried install via `pip install` and through a local clone with `python setup.py install`. The installation is successful, but on execution of a script I run into this error: 

```bash
import tinycudann as tcnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../tiny-cuda-nn/bindings/torch/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/.../tiny-cuda-nn/bindings/torch/tinycudann/modules.py", line 50, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/home/.../lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/.../lib/python3.8/site-packages/tinycudann-1.7-py3.8-linux-x86_64.egg/tinycudann_bindings/_86_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv
```

Here's my system info:
 OS: Ubuntu 22.04.2 LTS
 Python: Python 3.8.5
 PyTorch: pytorch-2.0.0 
 GCC/G++: 11.3.0/11.3.0
 CUDA: release 11.7, V11.7.99

Thank you for your help!

**Comment by geyang** [comment]
Does this issue still persist?

**Comment by suddhu** [comment]
Yup! Still does.

**Comment by suddhu** [comment]
Resolved, downgrading from gcc/g++ 11 to 9 fixed this issue!

**Comment by sjtuytc** [comment]
not resolved with gcc/ g++ version = 9

**Comment by learn2phoenix** [comment]
Have the same issue, does anyone know a solution?
