### ISSUE TITLE
 python setup.py install   Error compiling objects for extension

### ISSUE THREAD

**Issue by BCL123456-BAL** [NVlabs/tiny-cuda-nn#291]
My operating system is windows11, cuda version is 11.6, cmake is 3.24.3, visual studio 2022.

An error occurred when I ran python setup.py install. The complete error log is as follows：

(base) D:\Desktop\tiny-cuda-nn\bindings\torch>python setup.py install
Building PyTorch extension for tiny-cuda-nn version 1.7
Obtained compute capability 86 from PyTorch
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
Detected CUDA version 11.6
running install
D:\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
D:\anaconda3\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing tinycudann.egg-info\PKG-INFO
writing dependency_links to tinycudann.egg-info\dependency_links.txt
writing top-level names to tinycudann.egg-info\top_level.txt
reading manifest file 'tinycudann.egg-info\SOURCES.txt'
writing manifest file 'tinycudann.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'tinycudann_bindings._86_C' extension
Emitting ninja build file D:\Desktop\tiny-cuda-nn\bindings\torch\build\temp.win-amd64-cpython-38\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
D:\anaconda3\lib\site-packages\ninja\data\bin\ninja: invalid option -- `-e'
usage: ninja [options] [targets...]

if targets are unspecified, builds the 'default' target (see manual).

options:
  --version      print ninja version ("1.11.1.git.kitware.jobserver-1")
  -v, --verbose  show all command lines while building
  --quiet        don't show progress status, just command output

  -C DIR   change to DIR before doing anything else
  -f FILE  specify input build file [default=build.ninja]

  -j N     run N jobs in parallel (0 means infinity) [default=14 on this system]
  -k N     keep going until N jobs fail (0 means infinity) [default=1]
  -l N     do not start new jobs if the load average is greater than N
  -n       dry run (don't run commands but act like they succeeded)

  -d MODE  enable debugging (use '-d list' to list modes)
  -t TOOL  run a subtool (use '-t list' to list subtools)
    terminates toplevel options; further flags are passed to the tool
  -w FLAG  adjust warnings (use '-w list' to list warnings)
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1900, in _run_ninja_build
    subprocess.run(
  File "D:\anaconda3\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-version']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 174, in <module>
    setup(
  File "D:\anaconda3\lib\site-packages\setuptools\__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\anaconda3\lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "D:\anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\dist.py", line 1221, in run_command
    super().run_command(command)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 843, in build_extensions
    build_ext.build_extensions(self)
  File "D:\anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\anaconda3\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 815, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1573, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

I changed ['ninja', '-v'] in D:\anaconda3\lib\site-packages\torch\utils\cpp_extension.py" to ['ninja', '-version'] and ['ninja', '--v'] has no effect.

**Comment by daytoy314** [comment]
same question

**Comment by tb2-sy** [comment]
same question

**Comment by samcao416** [comment]
same question on cuda 11.8 win11 python 3.8

**Comment by samcao416** [comment]
Found a solution, worked for me.

Checkout:
https://github.com/NVlabs/tiny-cuda-nn/issues/195#issuecomment-1316275803

**Comment by BerryKanry114514** [comment]
> 

Works for me too! Thanks a lot!
