### ISSUE TITLE
 cudaEventCreate(&m_event) failed with error an illegal memory access was encountered

### ISSUE THREAD

**Issue by hanfeng-wu** [NVlabs/tiny-cuda-nn#302]
Thanks for the great work, I encounter an Error when trying to use your work in NerfStudio. I used your latest version and referenced the [https://github.com/nerfstudio-project/nerfstudio/issues/1534#issue-1602997372](url), yet not solve my problem. I wonder what could be the problem, since I can run with the same environment tinycudann with no problem.
```
Traceback (most recent call last):
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/scripts/train.py", line 247, in entrypoint
    main(
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/scripts/train.py", line 233, in main
    launch(
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/scripts/train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/scripts/train.py", line 87, in train_loop
    trainer.train()
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/engine/trainer.py", line 218, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/engine/trainer.py", line 392, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflpipeline.py", line 98, in get_train_loss_dict
    model_outputs = self.model(ray_bundle, batch['first_dist'])
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflmodel.py", line 164, in forward
    return self.get_outputs(ray_bundle, rays_dist)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflmodel.py", line 136, in get_outputs
    outputs = self.nfl_field.forward(ray_samples_uniform, rays_dist=rays_dist)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflfield.py", line 378, in forward
    density, density_embedding = self.get_density(ray_samples, rays_dist=rays_dist)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflfield.py", line 261, in get_density
    sigma, geo_feat = self.density(xyzs.view(-1,3))
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflfield.py", line 165, in density
    x_pos = self.hash_encoding(x)
  File "/scratch/hanfeng/LidarSimStudio/NFLStudio/nflfield.py", line 153, in hash_encoding
    x_pos = self.encoder_sigma(x)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/tinycudann-1.7-py3.10-linux-x86_64.egg/tinycudann/modules.py", line 177, in forward
    output = _module_function.apply(
  File "/scratch/hanfeng/anaconda3/envs/nerfstudio/lib/python3.10/site-packages/tinycudann-1.7-py3.10-linux-x86_64.egg/tinycudann/modules.py", line 89, in forward
    native_ctx, output = native_tcnn_module.fwd(input, params)
RuntimeError: /scratch/hanfeng/tiny-cuda-nn/include/tiny-cuda-nn/multi_stream.h:99 cudaEventCreate(&m_event) failed with error an illegal memory access was encountered
```

**Comment by VictoriaHY** [comment]
I also encountered this problem, have you solved it? Thanks!
