### ISSUE TITLE
tinycuda install error

### ISSUE THREAD

**Issue by hanjoonwon** [NVlabs/tiny-cuda-nn#344]
error occured  pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
windows 11,python=3.8,pytorch=1.12.1 cudatoolkit=11.6

error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 75 from PyTorch
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2023 NVIDIA Corporation
      Built on Mon_Apr__3_17:36:15_Pacific_Daylight_Time_2023
      Cuda compilation tools, release 12.1, V12.1.105
      Build cuda_12.1.r12.1/compiler.32688072_0
      Detected CUDA version 12.1
      Targeting C++ standard 17
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\modules.py -> build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\__init__.py -> build\lib.win-amd64-cpython-38\tinycudann
      running egg_info
      creating tinycudann.egg-info
      writing tinycudann.egg-info\PKG-INFO
      writing dependency_links to tinycudann.egg-info\dependency_links.txt
      writing top-level names to tinycudann.egg-info\top_level.txt
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      reading manifest file 'tinycudann.egg-info\SOURCES.txt'
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      copying tinycudann\bindings.cpp -> build\lib.win-amd64-cpython-38\tinycudann
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Master\AppData\Local\Temp\pip-req-build-ci4hqnpy\bindings/torch\setup.py", line 189, in <module>
          setup(
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\wheel\bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 434, in build_extensions
          self._check_cuda_version(compiler_name, compiler_version)
        File "C:\Users\Master\anaconda3\envs\sdfstudio\lib\site-packages\torch\utils\cpp_extension.py", line 812, in _check_cuda_version
          raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
      RuntimeError:
      The detected CUDA version (12.1) mismatches the version that was used to compile
      PyTorch (11.6). Please make sure to use the same CUDA versions.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects

**Comment by MYM181** [comment]
I have the same problem now.

**Comment by chris-aeviator** [comment]
I had a similar error that stated C++ > 11 is not supported, you seem to have c++ 17

**Comment by chris-aeviator** [comment]
pytorch is only availble for CUDA 11.7 & 11.8 AFAIK. You could try installing cuda 11.8

**Comment by hanjoonwon** [comment]
Thanks :)
-----Original Message-----
