### ISSUE TITLE
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

### ISSUE THREAD

**Issue by qiyang77** [NVlabs/tiny-cuda-nn#346]
I just can not install tinycudann on Windows as a Pytorch extension. I tried all methods I found but none of them work for me.
Python: 3.10
torch: 2.0.1
CUDA: 11.8

**Comment by qiyang77** [comment]
```
(nerfstudio38) C:\Users\yang8460>pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\yang8460\appdata\local\temp\pip-req-build-o3rgj9w_
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\yang8460\AppData\Local\Temp\pip-req-build-o3rgj9w_'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 28ca991f99b44d10387d73077c07ccfdd7f96275
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      'nvcc' is not recognized as an internal or external command,
      operable program or batch file.
      C:\Users\yang8460\AppData\Local\Temp\pip-req-build-o3rgj9w_\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\yang8460\AppData\Local\Temp\pip-req-build-o3rgj9w_\bindings/torch\setup.py", line 187, in <module>
          ext_modules = [make_extension(comp) for comp in compute_capabilities]
        File "C:\Users\yang8460\AppData\Local\Temp\pip-req-build-o3rgj9w_\bindings/torch\setup.py", line 187, in <listcomp>
          ext_modules = [make_extension(comp) for comp in compute_capabilities]
        File "C:\Users\yang8460\AppData\Local\Temp\pip-req-build-o3rgj9w_\bindings/torch\setup.py", line 172, in make_extension
          ext = CUDAExtension(
        File "C:\Users\yang8460\Anaconda3\envs\nerfstudio38\lib\site-packages\torch\utils\cpp_extension.py", line 1048, in CUDAExtension
          library_dirs += library_paths(cuda=True)
        File "C:\Users\yang8460\Anaconda3\envs\nerfstudio38\lib\site-packages\torch\utils\cpp_extension.py", line 1186, in library_paths
          paths.append(_join_cuda_home(lib_dir))
        File "C:\Users\yang8460\Anaconda3\envs\nerfstudio38\lib\site-packages\torch\utils\cpp_extension.py", line 2223, in _join_cuda_home
          raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 86 from PyTorch
      Targeting C++ standard 14
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by qiyang77** [comment]
I just found a way to avoid this issue. 
For Windows users, this issue is caused by missing cuda-nvcc, so just install it and everything will be fine.
```
conda install -c "nvidia/label/cuda-11.8.0" cuda-nvcc
https://anaconda.org/nvidia/cuda-nvcc
```

**Comment by xgh127** [comment]
It seems dosen't work for me.It still has the the same error

**Comment by Duodecimus** [comment]
I took a look at cpp_extension.py. 
Am I misremembering how python works, or are all references to CUDA_HOME in this thing local variables?
Adding `CUDA_HOME = _find_cuda_home()` before each time it gets checked, specifically _check_cuda_version and _join_cuda_home got me to the next step.
