### ISSUE TITLE
Why is it happen?

### ISSUE THREAD

**Issue by wpl427** [NVlabs/tiny-cuda-nn#362]
(codef) [root@prod-emr-gpu01 torch]# pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Looking in indexes: http://de.mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-lyo_m2r9
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-lyo_m2r9
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 6f018a9cd1b369bcb247e1d539968db8e48b2b3f
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      /tmp/pip-req-build-lyo_m2r9/bindings/torch/setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-lyo_m2r9/bindings/torch/setup.py", line 11, in <module>
          from torch.utils.cpp_extension import BuildExtension, CUDAExtension
        File "/data/miniconda3/envs/codef/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 19, in <module>
          from .hipify import hipify_python
        File "/data/miniconda3/envs/codef/lib/python3.9/site-packages/torch/utils/hipify/hipify_python.py", line 34, in <module>
          from .cuda_to_hip_mappings import CUDA_TO_HIP_MAPPINGS
        File "/data/miniconda3/envs/codef/lib/python3.9/site-packages/torch/utils/hipify/cuda_to_hip_mappings.py", line 34, in <module>
          rocm_path = subprocess.check_output(["hipconfig", "--rocmpath"]).decode("utf-8")
        File "/data/miniconda3/envs/codef/lib/python3.9/subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/data/miniconda3/envs/codef/lib/python3.9/subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/data/miniconda3/envs/codef/lib/python3.9/subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/data/miniconda3/envs/codef/lib/python3.9/subprocess.py", line 1837, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      NotADirectoryError: [Errno 20] Not a directory: 'hipconfig'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(codef) [root@prod-emr-gpu01 torch]# python
Python 3.9.17 | packaged by conda-forge | (main, Aug 10 2023, 07:02:31) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1+cu117
>>> print(torch.cuda.is_available())
True

**Comment by majingui** [comment]
I have the same problem as you, have you solved it?
