### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by glaciomarine** [NVlabs/tiny-cuda-nn#379]
ninja: error: '/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/fmt/src/format.cc', needed by '/home/cqu/go-slam/tiny-cuda-nn-master/bindings/torch/dependencies/fmt/src/format.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1746, in _run_ninja_build
    env=env)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 218, in <module>
    cmdclass={"build_ext": BuildExtension}
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 571, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1424, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by glaciomarine** [comment]
Change the setup.py file to “cmdclass={"build_ext":BuildExtension.with_options(use_ninja=False)}”
New error occurs
gcc -pthread -B /home/cqu/anaconda3/envs/go-slam/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cqu/go-slam/tiny-cuda-nn-master/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/cutlass/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/cutlass/tools/util/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/fmt/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/TH -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/cqu/anaconda3/envs/go-slam/include/python3.7m -c ../../dependencies/fmt/src/format.cc -o build/temp.linux-x86_64-3.7/../../dependencies/fmt/src/format.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=75 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=_75_C -D_GLIBCXX_USE_CXX11_ABI=0
gcc: error: ../../dependencies/fmt/src/format.cc:  No such file or directory
error: command '/usr/bin/gcc' failed with exit code 1

**Comment by loushengtao** [comment]
> Change the setup.py file to “cmdclass={"build_ext":BuildExtension.with_options(use_ninja=False)}” New error occurs gcc -pthread -B /home/cqu/anaconda3/envs/go-slam/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/cqu/go-slam/tiny-cuda-nn-master/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/cutlass/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/cutlass/tools/util/include -I/home/cqu/go-slam/tiny-cuda-nn-master/dependencies/fmt/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/TH -I/home/cqu/anaconda3/envs/go-slam/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda-11.3/include -I/home/cqu/anaconda3/envs/go-slam/include/python3.7m -c ../../dependencies/fmt/src/format.cc -o build/temp.linux-x86_64-3.7/../../dependencies/fmt/src/format.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=75 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=_75_C -D_GLIBCXX_USE_CXX11_ABI=0 gcc: error: ../../dependencies/fmt/src/format.cc: No such file or directory error: command '/usr/bin/gcc' failed with exit code 1

I met the same problem, how did you solve it?

**Comment by codyreading** [comment]
Hello!

I found this happens when I use `python setup.py install`, turns out I was just missing the files in the submodules.

You can do a `git clone --recursive git@github.com:NVlabs/tiny-cuda-nn.git` when cloning to resolve this.

**Comment by AlecDusheck** [comment]
@codyreading thank you for saving me hours sir. looking back at it, install instructions in the README mention this but it's a very confusing error if you git clone this yourself
