### ISSUE TITLE
ninja error: missing and no known rule

### ISSUE THREAD

**Issue by Planetinaline** [NVlabs/tiny-cuda-nn#390]
>>> torch.__version__
'2.0.0+cu117'
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

(magic3d) root@autodl-container-29624db78d-2ef2dd5b:~/dreamfusionacc-master/tiny-cuda-nn-master/bindings/torch# python setup.py install
/root/dreamfusionacc-master/tiny-cuda-nn-master/bindings/torch/setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Building PyTorch extension for tiny-cuda-nn version 1.7
Obtained compute capability 89 from PyTorch
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
Detected CUDA version 11.8
Targeting C++ standard 17
running install
/root/miniconda3/envs/magic3d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/root/miniconda3/envs/magic3d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing tinycudann.egg-info/PKG-INFO
writing dependency_links to tinycudann.egg-info/dependency_links.txt
writing top-level names to tinycudann.egg-info/top_level.txt
reading manifest file 'tinycudann.egg-info/SOURCES.txt'
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
/root/miniconda3/envs/magic3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py:388: UserWarning: The detected CUDA version (11.8) has a minor version mismatch with the version that was used to compile PyTorch (11.7). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/root/miniconda3/envs/magic3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py:398: UserWarning: There are no g++ version bounds defined for CUDA version 11.8
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'tinycudann_bindings._89_C' extension
Emitting ninja build file /root/dreamfusionacc-master/tiny-cuda-nn-master/bindings/torch/build/temp.linux-x86_64-cpython-39/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '/root/dreamfusionacc-master/tiny-cuda-nn-master/dependencies/fmt/src/format.cc', needed by '/root/dreamfusionacc-master/tiny-cuda-nn-master/bindings/torch/dependencies/fmt/src/format.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/root/miniconda3/envs/magic3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1893, in _run_ninja_build
    subprocess.run(
  File "/root/miniconda3/envs/magic3d/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

**Comment by Planetinaline** [comment]
i just opened the /root/dreamfusionacc-master/tiny-cuda-nn-master/dependencies/fmt/src/ file and saw nothing in it.
and i checked the origin code and found fmt and cutlass file have new editions, which the github failed to download for me...
problem solved

**Comment by 3dprintscanner** [comment]
When cloning the repo, make sure to `git clone --recurse-submodules` or `git submodule update --init --recursive` if you already have the repo as those missing filesare contained in the fmt submodule.
