### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by hanjoonwon** [NVlabs/tiny-cuda-nn#398]
![image](https://github.com/NVlabs/tiny-cuda-nn/assets/125524043/83251a26-5aa6-478d-8c76-3b31e9c7ca08)
Can you help me with what's wrong with the error? To use the 3d reconstruction model, I received several packages to use sdfstudio and checked that they all exist in the condalist. But when I ran it, I couldn't find the tcnn, so I checked with import and found that this error occurred. Windows is using it as an anaconda in wsl2 Ubuntu environment

**Comment by jaymdq** [comment]
Similar error here...

```python
>>> import tinycudann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/opt/conda/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
    _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
  File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/conda/lib/python3.10/site-packages/tinycudann_bindings/_86_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
```

@hanjoonwon did you find a solution for this?

**Comment by hanjoonwon** [comment]
> Similar error here...
> 
> ```python
> >>> import tinycudann
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/opt/conda/lib/python3.10/site-packages/tinycudann/__init__.py", line 9, in <module>
>     from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
>   File "/opt/conda/lib/python3.10/site-packages/tinycudann/modules.py", line 51, in <module>
>     _C = importlib.import_module(f"tinycudann_bindings._{cc}_C")
>   File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
> ImportError: /opt/conda/lib/python3.10/site-packages/tinycudann_bindings/_86_C.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda20CUDACachingAllocator9allocatorE
> ```
> 
> @hanjoonwon did you find a solution for this?

I don't remember, but I think I changed the graphics card driver version or changed the CUDA version and it worked.

**Comment by FRACtURE-HiKARi** [comment]
@hanjoonwon I am also using anaconda and WSL2 Ubuntu environment with RTX 4060. Could you provide the working version of the possibly related tools? It would help a lot.
