### ISSUE TITLE
ERROR wile downloading tiny-cuda-nn

### ISSUE THREAD

**Issue by Tarpita-Singh** [NVlabs/tiny-cuda-nn#441]
I was following the NeRF Studio documentation for installation and i came across an error while executing this line:

tiny-cuda-nn
After pytorch and ninja, install the torch bindings for tiny-cuda-nn:

`pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

the error :

(nerfstudio) C:\Users\TARPITA>pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\tarpita\appdata\local\temp\pip-req-build-tu2nu7o_
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\TARPITA\AppData\Local\Temp\pip-req-build-tu2nu7o_'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit 4892659e015b12bd2fce446b8a8e33e646b21746
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      C:\Users\TARPITA\AppData\Local\Temp\pip-req-build-tu2nu7o_\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      No CUDA runtime is found, using CUDA_HOME='C:\Users\TARPITA\anaconda3\envs\nerfstudio'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\TARPITA\AppData\Local\Temp\pip-req-build-tu2nu7o_\bindings/torch\setup.py", line 51, in <module>
          raise EnvironmentError("Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.")
      OSError: Unknown compute capability. Specify the target compute capabilities in the TCNN_CUDA_ARCHITECTURES environment variable or install PyTorch with the CUDA backend to detect it automatically.
      Building PyTorch extension for tiny-cuda-nn version 1.7
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

i have tried a few solutions mentioned here but still cannot find a way to resolve this.
if you have solved a similar problem then please help me, thanks.

**Comment by Duodecimus** [comment]
you need to add the environment variable 'TCNN_CUDA_ARCHITECTURES'
look up your card on https://developer.nvidia.com/cuda-gpus and remove punctuation from it (ex the 3050's 8.6 should be 86 in your system path)
