### ISSUE TITLE
invailid ID issue - install error

### ISSUE THREAD

**Issue by SamanthaZH** [NVlabs/tiny-cuda-nn#449]
I suddenly met this error when I installed tinycudann. 
 " Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-6eqgjbkw/bindings/torch/setup.py", line 47, in <module>
          major, minor = torch.cuda.get_device_capability()
        File ".../lib/python3.9/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
          prop = get_device_properties(device)
        File ".../lib/python3.9/site-packages/torch/cuda/__init__.py", line 374, in get_device_properties
          raise AssertionError("Invalid device id")
      AssertionError: Invalid device id"

**Comment by SamanthaZH** [comment]
Update with "
pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116 "
"pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch" and I also tried with local installation,. both got same error. 

 Cloning https://github.com/NVlabs/tiny-cuda-nn/ to /tmp/pip-req-build-d02z_270
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ /tmp/pip-req-build-d02z_270
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit daf9628c8d4500aee29935e15cff58a359277ad0
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-d02z_270/bindings/torch/setup.py", line 47, in <module>
          major, minor = torch.cuda.get_device_capability()
        File "/home/jzhou23/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 357, in get_device_capability
          prop = get_device_properties(device)
        File "/home/jzhou23/.local/lib/python3.9/site-packages/torch/cuda/__init__.py", line 374, in get_device_properties
          raise AssertionError("Invalid device id")
      AssertionError: Invalid device id
      Building PyTorch extension for tiny-cuda-nn version 1.7
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
