### ISSUE TITLE
Error during python setup.py install

### ISSUE THREAD

**Issue by Kkkassini** [NVlabs/tiny-cuda-nn#459]
FAILED: /userfs/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-39/tinycudann/bindings.o 
c++ -MMD -MF /userfs/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-39/tinycudann/bindings.o.d -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/userfs/tiny-cuda-nn/include -I/userfs/tiny-cuda-nn/dependencies -I/userfs/tiny-cuda-nn/dependencies/cutlass/include -I/userfs/tiny-cuda-nn/dependencies/cutlass/tools/util/include -I/userfs/tiny-cuda-nn/dependencies/fmt/include -I/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include -I/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/torch/csrc/api/include -I/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/TH -I/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/THC -I/usr/local/cuda/include -I/userfs/env/threestudio_env/include -I/usr/include/python3.9 -c -c /userfs/tiny-cuda-nn/bindings/torch/tinycudann/bindings.cpp -o /userfs/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-39/tinycudann/bindings.o -std=c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=89 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_89_C -D_GLIBCXX_USE_CXX11_ABI=0
In file included from /userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/torch/csrc/Device.h:4,
                 from /userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/python.h:8,
                 from /userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/torch/extension.h:9,
                 from /userfs/tiny-cuda-nn/bindings/torch/tinycudann/bindings.cpp:34:
/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/include/torch/csrc/python_headers.h:12:10: fatal error: Python.h: No such file or directory
   12 | #include <Python.h>
      |          ^~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/userfs/tiny-cuda-nn/bindings/torch/setup.py", line 189, in <module>
    setup(
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
    self.run_command(cmd)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/install.py", line 92, in run
    self.do_egg_install()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/install.py", line 144, in do_egg_install
    self.run_command('bdist_egg')
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/install_lib.py", line 13, in run
    self.build()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
    super().run_command(command)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
    cmd_obj.run()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/build_ext.py", line 93, in run
    _build_ext.run(self)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/utils/cpp_extension.py", line 870, in build_extensions
    build_ext.build_extensions(self)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
    _build_ext.build_extension(self, ext)
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/utils/cpp_extension.py", line 683, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/userfs/env/threestudio_env/lib64/python3.9/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by booker-max** [comment]
I also encountered the same problem, have you solved it?

**Comment by XiaozhenQiao** [comment]
I also encountered the same problem, have you solved it?

**Comment by 12345678901234567800001882277777** [comment]
> I also encountered the same problem, have you solved it?

 I have the same problem, have you solved it?!!!!!!
