### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by 12345678901234567800001882277777** [NVlabs/tiny-cuda-nn#477]
python3.8/site-packages/tiny-cuda-nn/bindings/torch$ python setup.py install
setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_version
Building PyTorch extension for tiny-cuda-nn version 1.7
/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/cuda/__init__.py:104: UserWarning: 
NVIDIA GeForce RTX 4090 with CUDA capability sm_89 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_35 sm_50 sm_60 sm_61 sm_70 sm_75 compute_50.
If you want to use the NVIDIA GeForce RTX 4090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Obtained compute capability 89 from PyTorch
Detected CUDA version 11.5
WARNING: Compute capabilities [89] are not all supported by the installed CUDA version 11.5. Targeting [86] instead.
Targeting C++ standard 17
running install
/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
writing tinycudann.egg-info/PKG-INFO
writing dependency_links to tinycudann.egg-info/dependency_links.txt
writing top-level names to tinycudann.egg-info/top_level.txt
reading manifest file 'tinycudann.egg-info/SOURCES.txt'
writing manifest file 'tinycudann.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying tinycudann/modules.py -> build/lib.linux-x86_64-cpython-38/tinycudann
copying tinycudann/__init__.py -> build/lib.linux-x86_64-cpython-38/tinycudann
copying tinycudann/bindings.cpp -> build/lib.linux-x86_64-cpython-38/tinycudann
running build_ext
building 'tinycudann_bindings._86_C' extension
Emitting ninja build file /home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/tiny-cuda-nn/bindings/torch/build/temp.linux-x86_64-cpython-38/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: error: '/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/tiny-cuda-nn/dependencies/fmt/src/format.cc', needed by '/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/tiny-cuda-nn/bindings/torch/dependencies/fmt/src/format.o', missing and no known rule to make it
Traceback (most recent call last):
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 227, in <module>
    setup(
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 183, in setup
    return run_commands(dist)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
    dist.run_commands()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/install.py", line 96, in run
    self.do_egg_install()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/install.py", line 148, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 177, in run
    cmd = self.call_command('install_lib', warn_dir=False)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 163, in call_command
    self.run_command(cmdname)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 19, in run
    self.build()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 110, in build
    self.run_command('build_ext')
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/dist.py", line 999, in run_command
    super().run_command(command)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
    cmd_obj.run()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 98, in run
    _build_ext.run(self)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 476, in build_extensions
    self._build_extensions_serial()
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 502, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 263, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 557, in build_extension
    objects = self.compiler.compile(
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 529, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1354, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/home/lizhengdan/miniconda3/envs/scope/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

For the aforementioned issue, I hope to receive some assistance.

**Comment by TonyHongtaoWu** [comment]
I have the same issue

**Comment by 12345678901234567800001882277777** [comment]
> I have the same issue

First, there was an error: RuntimeError: Error compiling objects for extension.
Then, in the setup.py file, change
cmdclass={'build_ext': BuildExtension}
to
cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)}.

After that, there was another error: error: command '/usr/bin/nvcc' failed with exit code 1.
Using sudo find / -name "nvcc" to locate the nvcc of the CUDA installation (version 11.6),
edit the ~/.bashrc file :

vim ~/.bashrc
export CUDA_HOME=/home/li/miniconda3/pkgs/cuda-11.6
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib:$LD_LIBRARY_PATH

source ~/.bashrc

Finally, the download of the tinycudann package was completed

This is my solution, hope it helps you.
